# 다시 보는 초난감 DAO

## 기존 코드에 추가적으로 예외 상황에 대한 처리가 필요함

### DB 커넥션이라는 제한적인 리소스를 공유해 사용하는 서버에서 동작하는 JDBC 코드에는 반드시 지켜야 할 원칙이 있음 -> 예외가 발생했을 경우에 사용한 리소스를 반드시 반환하도록 만들어야함

```
//JDBC API를 이용한 DAO 코드인 deleteAll()

public void deleteAll() throws SQLException {
	Connection c = dataSource.getConnection();

    	PreparedStatement ps = c.prepareStatement("delete from users");
    	ps.executeUpdate();
        //위에서 예외 발생하면 바로 메소드 실행이 중단됨

        ps.close();
        c.close();
}
```

## 위 메서드에서 발생하는 상황

    1. Connection과 PreparedStatement라는 두 개의 공유 리소스를 가져와서 사용
    2. 정상적으로 처리되면 메서드를 마치기 전 close()를 호출해 리소스를 반환
    3. 만약 PreparedStatement를 처리하는 와중에 예외가 발생하면 메소드를 끝내지 못하고 메소드를 빠져나가게 됨
    4. 따라서, 리소스가 제대로 반환되지 않아 커넥션 풀에 여유가 없어 리소스가 부족하게 됨

### 예외상황 발생하면 리소스를 반환하도록 수정

```
//예외 발생 시에도 리소스를 반환하도록 수정한 deleteAll()

public void deleteAll() throws SQLException {
	Connection c = null;
    	PreparedStatement ps = null;

        try {
        	c = dataSource.getConnection();
            	ps = c.prepareStatement("delete from users");
                ps.executeUpdate();
        } catch (SQLException e) {
        	throw e;
        } finally {
        	if (ps != null) {
            		try  {
                    		ps.close();
                        } catch (SQLException e) {
                        }
                }
                if (c != null) {
                	try {
                    		c.close();
                        } catch (SQLException e) {
                        }
                }
        }
}
```

### try 블록에서 예외가 발생했을 때나 아닐 때 모두 finally를 최종적으로 통과하므로 리소스를 반환하게 됨

## JDBC 조회 기능 예외처리

```
//JDBC 예외처리를 적용한 getCount() 메소드 => 등록된 User의 수를 가져옴

public int getCount() throws SQLException {
	Connection c = null;
    	PreparedStatement ps = null;
        ResultSet rs = null;

        try {
        	c = dataSource.getConnection();

                ps = c.prepareStatement("select count(*) from users");

                rs = ps.executeQuery();
                rs.next();
                return rs.getInt(1)
        } catch (SQLException e) {
        	throw e;
        } finally {
        	if (rs != null) {
            		try {
                    		rs.close();
                        } catch (SQLException e) {
                        }
                }
                if (ps != null) {
                	try {
                    		ps.close();
                        } catch (SQLException e) {
                        }
                }
                if (c != null) {
                	try {
                    		c.close();
                        } catch (SQLException e) {
                        }
                }
	}
}
```

### ResultSet을 닫아주는 기능을 추가
